variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - test
  - badges

image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_gcc:v9.3.0

before_script:
  - apt update
  - apt install -y python3
  - apt install -y python3-pip
  - python3 --version  # For debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build:
  cache:
    paths:
      - .cache/pip
      - venv/

  stage: build
  tags:
    - x86_64
    - linux
    - docker

  artifacts:
    name: aff3ct
    paths:
      - aff3ct
      - venv

  script:
    - export CC="gcc"
    - export CXX="g++"
    - pip3 install ../pyaf-core -v

test:
  cache:
    paths:
      - .cache/pip
      - venv/

  stage: test

  dependencies:
  - build

  tags:
  - x86_64
  - linux
  - docker

  script:
    - cd ..
    - pip3 show -f aff3ct
    - pytest --pyargs aff3ct --junitxml=./pyaf-core/report.xml
    
  artifacts:
    when: always
    reports:
      junit: report.xml

badges:
  stage: badges
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRIVATE_TOKEN: $ACCESS_TOKEN
  cache:
    key: badges
    paths:
      - .cache/pip
      - venv/
  script:
     - pip3 install badges-gitlab
     - badges-gitlab -V
     - badges-gitlab
  artifacts:
    when: always
    paths:
      - public/badges/*.svg
    expire_in: 3 months
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
      allow_failure: true

