[build-system]
requires = [
    "wheel",
    "setuptools",
    "cmake",
    "ninja; platform_system!='Windows'",
]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "aff3ct"
version = "0.0.1"
authors = [{name = "Romain Tajan", email= "romain.tajan@ims-bordeaux.fr"}]
requires-python = ">=3.8"
description = "Python wrapper for AFF3CT-core library."
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "graphviz",
    "numpy",
    "multipledispatch",
    "pytest>=6.0"
]

[project.optional-dependencies]
tests = [
  "pytest>=6.0",
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "test"
]

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"
build-verbosity = 3
test-requires = "pytest"
test-command = "pytest --pyargs aff3ct --junitxml=./pyaf-core/report.xml"

[tool.badges_gitlab]
path = "public/badges"
# junit_xml = "tests/report.xml"
# List of Lists Format [["label", "message", "color"]]
static_badges = [["conventional commits", "1.0.0", "yellow"]]
link_badges = ['https://img.shields.io/pypi/wheel/badges-gitlab']
