name: ci
on: [push]
permissions:
  contents: write
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build
        run: |
          git submodule update --init --recursive
          pip install --upgrade pip
          python -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          export GIT_TAG="v0.0.0"
          pip install -v -Ccmake.define.SPU_OVERRIDE_VERSION="$GIT_TAG" .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: env
  deploy:
    if: contains( github.ref, 'actions_github')
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: env
          path: env/
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          python -m venv env
          source env/bin/activate
          pip install mkdocs-material
          pip install mkdocs-jupyter
          pip install mkdocstrings-python
          mkdocs gh-deploy --force