name: ci
on: [push]
permissions:
  contents: write
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_gcc:v9.3.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install . -v
        shell: bash
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv
  deploy:
    if: contains( github.ref, 'develop')
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: venv/
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install mkdocs-material
          pip install mkdocs-jupyter
          pip install mkdocstrings-python
          mkdocs gh-deploy --force